name: ohw-espanol-web
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - pip
  - jupyter-book
  - ipykernel
  - ghp-import
  - pandas
  # - geopandas
  # - xarray
  - matplotlib
  # - seaborn
  # - folium
  # - cartopy

